### ISSUE TITLE
Support on linux?

### ISSUE THREAD

**Issue by crackedpotato007** [Dhravya/readme-generator#5]
From your Readme it appears that the program is windows only. I have no idea about how rust works if it's platform independent or not

**Comment by Dhravya** [comment]
I'm pretty sure that this will work in linux, but i haven't tested it yet. Can someone please try out the command and let me know?

**Comment by Dumbo-programmer** [comment]
Hi,I have added linux support and it works so rest assured.

**Comment by Dhravya** [comment]
Alright, this issue seems to be resolved now! Thanks for your contribution @Dumbo-programmer
